# Generated by Django 3.1.2 on 2020-11-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
