# Generated by Django 3.1.2 on 2021-01-23 08:08

import board.helpers.images
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория животных',
                'verbose_name_plural': 'Категории животных',
                'db_table': 'pet_category',
            },
        ),
        migrations.CreateModel(
            name='PetSubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название подкатегории')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_subcategory', to='board.petcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория животных',
                'verbose_name_plural': 'Подкатегории животных',
                'db_table': 'pet_subcategory',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('title', models.CharField(max_length=200, verbose_name='Название объявления')),
                ('year_of_birth', models.IntegerField(null=True, verbose_name='Год рождения')),
                ('month_of_birth', models.IntegerField(null=True, verbose_name='Месяц рождения')),
                ('day_of_birth', models.IntegerField(null=True, verbose_name='День рождения')),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время создания объявления')),
                ('update_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время обновления объявления')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_post', to='board.petsubcategory', verbose_name='Подкатегория объявления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_pets', to='accounts.account', verbose_name='Автор объявления')),
            ],
            options={
                'verbose_name': 'Объявление о животном',
                'verbose_name_plural': 'Объявления о животных',
                'db_table': 'post',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('url', models.FileField(null=True, upload_to=board.helpers.images.get_upload_path)),
                ('order', models.IntegerField(default=1, verbose_name='Порядок в объявлении')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='board.post')),
            ],
            options={
                'verbose_name': 'Фотография объявления животных',
                'verbose_name_plural': 'Фотографии объявления животных',
                'db_table': 'images',
            },
        ),
    ]
