# Generated by Django 3.1.2 on 2021-03-14 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_post', to='board.petcategory', verbose_name='Категория объявления'),
            preserve_default=False,
        ),
    ]
