# Generated by Django 3.1.2 on 2020-11-08 01:23

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_phone'),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostPets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('title', models.CharField(max_length=200, verbose_name='Название объявления')),
                ('year_of_birth', models.IntegerField(verbose_name='Год рождения')),
                ('month_of_birth', models.IntegerField(verbose_name='Месяц рождения')),
                ('day_of_birth', models.IntegerField(verbose_name='День рождения')),
                ('creation_date', models.DateTimeField(default='django.utils.timezone.now', verbose_name='Дата создания объявления')),
                ('update_date', models.DateTimeField(default='django.utils.timezone.now', verbose_name='Дата создания объявления')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.petsubcategory', verbose_name='Подкатегория объявления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_pets', to='accounts.account', verbose_name='Автор объявленимя')),
            ],
            options={
                'verbose_name': 'Объявление о животном',
                'verbose_name_plural': 'Объявления о животных',
                'db_table': 'post_pets',
            },
        ),
        migrations.CreateModel(
            name='PostHabitat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('title', models.CharField(max_length=200, verbose_name='Название объявления')),
                ('creation_date', models.DateTimeField(default='django.utils.timezone.now', verbose_name='Дата создания объявления')),
                ('update_date', models.DateTimeField(default='django.utils.timezone.now', verbose_name='Дата создания объявления')),
                ('for_pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.petsubcategory', verbose_name='Для животного')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_habitats', to='accounts.account', verbose_name='Автор объявленимя')),
            ],
            options={
                'verbose_name': 'Объявление о хабитате',
                'verbose_name_plural': 'Объявления о хабитатах',
                'db_table': 'post_habitat',
            },
        ),
        migrations.CreateModel(
            name='PostFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('title', models.CharField(max_length=200, verbose_name='Название объявления')),
                ('creation_date', models.DateTimeField(default='django.utils.timezone.now', verbose_name='Дата создания объявления')),
                ('update_date', models.DateTimeField(default='django.utils.timezone.now', verbose_name='Дата создания объявления')),
                ('for_pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.petsubcategory', verbose_name='Для животного')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_food', to='accounts.account', verbose_name='Автор объявленимя')),
            ],
            options={
                'verbose_name': 'Объявление о еде',
                'verbose_name_plural': 'Объявления о еде',
                'db_table': 'post_food',
            },
        ),
    ]
