# Generated by Django 3.1.2 on 2020-11-08 04:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_postfood_posthabitat_postpets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfood',
            name='photos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FileField(max_length=200, upload_to=''), size=None),
        ),
    ]
