# Generated by Django 3.1.2 on 2021-03-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_petsubcategory_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petsubcategory',
            name='photo',
        ),
        migrations.AddField(
            model_name='petsubcategory',
            name='photo_url',
            field=models.CharField(default=1, max_length=1024, verbose_name='URL фотографии'),
            preserve_default=False,
        ),
    ]
