# Generated by Django 3.1.2 on 2020-11-08 13:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_phone'),
        ('board', '0004_auto_20201108_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfood',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время создания объявления'),
        ),
        migrations.AlterField(
            model_name='postfood',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время обновления объявления'),
        ),
        migrations.AlterField(
            model_name='postfood',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_food', to='accounts.account', verbose_name='Автор объявления'),
        ),
        migrations.AlterField(
            model_name='posthabitat',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время создания объявления'),
        ),
        migrations.AlterField(
            model_name='posthabitat',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время обновления объявления'),
        ),
        migrations.AlterField(
            model_name='posthabitat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_habitats', to='accounts.account', verbose_name='Автор объявления'),
        ),
        migrations.AlterField(
            model_name='postpets',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время создания объявления'),
        ),
        migrations.AlterField(
            model_name='postpets',
            name='day_of_birth',
            field=models.IntegerField(null=True, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='postpets',
            name='month_of_birth',
            field=models.IntegerField(null=True, verbose_name='Месяц рождения'),
        ),
        migrations.AlterField(
            model_name='postpets',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='postpets',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время обновления объявления'),
        ),
        migrations.AlterField(
            model_name='postpets',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_pets', to='accounts.account', verbose_name='Автор объявления'),
        ),
        migrations.AlterField(
            model_name='postpets',
            name='year_of_birth',
            field=models.IntegerField(null=True, verbose_name='Год рождения'),
        ),
        migrations.CreateModel(
            name='PetsImageModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('mainimage', models.FileField(null=True, upload_to='images')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='board.postpets')),
            ],
            options={
                'verbose_name': 'Фотография объявления животных',
                'verbose_name_plural': 'Фотографии объявления животных',
                'db_table': 'pets_images',
            },
        ),
        migrations.CreateModel(
            name='HabitatImageModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('mainimage', models.FileField(null=True, upload_to='images')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='board.posthabitat')),
            ],
        ),
        migrations.CreateModel(
            name='FoodImageModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('mainimage', models.FileField(null=True, upload_to='images')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='board.postfood')),
            ],
        ),
    ]
