# Generated by Django 3.1.2 on 2020-11-08 13:45

import board.helpers.images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20201108_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='petsimagemodel',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Порядок в объявлении'),
        ),
        migrations.AlterField(
            model_name='petsimagemodel',
            name='mainimage',
            field=models.FileField(null=True, upload_to=board.helpers.images.get_upload_path),
        ),
    ]
